name: canteenlib
description: Library for communication with the czech canteen food ordering system iCanteen
version: 4.2.0
repository: "https://github.com/App-Elevate/AUT.canteenlib"
issue_tracker: "https://github.com/App-Elevate/AUT.canteenlib/issues"

environment:
  sdk: ">=2.16.1 <4.0.0"

dev_dependencies:
  build_runner: ^2.4.13
  dotenv: ^4.0.1
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  lints: ^3.0.0
  test: ^1.16.0
dependencies:
  http: ^1.1.0
  html: ^0.15.4
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
